window.PizzaTypes = {
  normal: "normal",
  spicy: "spicy",
  veggie: "veggie",
  fungi: "fungi",
  chill: "chill",
};

window.Pizzas = {
  n001: {
    name: "Slice Samurai",
    description: "A taste so sharp you'll bleed!",
    type: PizzaTypes.normal,
    typeAdv: null,
    typeWeak: null,
    src: "/images/characters/pizzas/n001.png",
    icon: "",
    actions: ["damage1", "dot1", "saucyStatus"],
    attributes: {
      vit: 20,
      vitRate: 2,
      atk: 10,
      atkRate: 2,
      def: 10,
      defRate: 2,
      spd: 10,
      spdRate: 2,
    },
  },
  n002: {
    name: "Alfredo Snake-eyes",
    description: "At least one of those olives is explosive",
    type: PizzaTypes.normal,
    typeAdv: null,
    typeWeak: null,
    src: "/images/characters/pizzas/n002.png",
    icon: "",
    actions: ["damage2", "multi1", "saucyStatus", "damage1"],
    attributes: {
      vit: 24,
      vitRate: 2,
      atk: 12,
      atkRate: 1,
      def: 5,
      defRate: 4,
      spd: 9,
      spdRate: 2,
    },
  },
  s001: {
    name: "Bacon Brigade",
    description: "A salty warrior who fears nothing",
    type: PizzaTypes.spicy,
    typeAdv: PizzaTypes.veggie,
    typeWeak: PizzaTypes.chill,
    src: "/images/characters/pizzas/s001.png",
    icon: "/images/icons/spicy.png",
    actions: ["damage1", "spicy1", "clumsyStatus"],
    attributes: {
      vit: 25,
      vitRate: 2,
      atk: 8,
      atkRate: 2,
      def: 10,
      defRate: 2,
      spd: 7,
      spdRate: 2,
    },
  },
  s002: {
    name: "Deep Dish Volcano",
    description: "A molten melody of four spiced cheeses",
    type: PizzaTypes.spicy,
    typeAdv: PizzaTypes.veggie,
    typeWeak: PizzaTypes.chill,
    src: "/images/characters/pizzas/s002.png",
    icon: "/images/icons/spicy.png",
    actions: ["damage1", "spicy2", "spicy+dot1", "clumsyStatus"],
    attributes: {
      vit: 24,
      vitRate: 2,
      atk: 11,
      atkRate: 1,
      def: 9,
      defRate: 4,
      spd: 6,
      spdRate: 2,
    },
  },
  v001: {
    name: "Kale-eye-descope",
    description: "A Healthy and mysterious fighter",
    type: PizzaTypes.veggie,
    typeAdv: PizzaTypes.fungi,
    typeWeak: PizzaTypes.spicy,
    src: "/images/characters/pizzas/v001.png",
    icon: "/images/icons/veggie.png",
    actions: ["veggie1", "dot2", "clumsyStatus"],
    attributes: {
      hp: 19,
      vitRate: 2,
      atk: 13,
      atkRate: 2,
      def: 4,
      defRate: 4,
      spd: 14,
      spdRate: 1,
    },
  },
  v002: {
    name: "Spinning Spinach",
    description: "Lithe and leafy with deadly accuracy",
    type: PizzaTypes.veggie,
    typeAdv: PizzaTypes.fungi,
    typeWeak: PizzaTypes.spicy,
    src: "/images/characters/pizzas/v002.png",
    icon: "/images/icons/veggie.png",
    actions: ["veggie1", "damage2", "veggie+dot2", "speed1"],
    attributes: {
      hp: 21,
      vitRate: 2,
      atk: 9,
      atkRate: 1,
      def: 8,
      defRate: 4,
      spd: 12,
      spdRate: 2,
    },
  },
  f001: {
    name: "Portobello Express",
    description: "A stalwart fungal defender",
    type: PizzaTypes.fungi,
    typeAdv: PizzaTypes.chill,
    typeWeak: PizzaTypes.veggie,
    src: "/images/characters/pizzas/f001.png",
    icon: "/images/icons/fungi.png",
    actions: ["fungi1", "dot1", "defense1"],
    baseStats: {
      hp: 28,
      vitRate: 2,
      atk: 8,
      atkRate: 2,
      def: 10,
      defRate: 1,
      spd: 4,
      spdRate: 4,
    },
  },
  f002: {
    name: "Chanterella",
    description: "A fragrant and graceful combatant",
    type: PizzaTypes.fungi,
    typeAdv: PizzaTypes.chill,
    typeWeak: PizzaTypes.veggie,
    src: "/images/characters/pizzas/f002.png",
    icon: "/images/icons/fungi.png",
    actions: ["damage1", "fungi2", "speed1", "dot1"],
    baseStats: {
      hp: 23,
      vitRate: 2,
      atk: 8,
      atkRate: 2,
      def: 8,
      defRate: 4,
      spd: 11,
      spdRate: 1,
    },
  },
  c001: {
    name: "Pineapple Powerhouse",
    description: "This frosty fighter is too cruel for school",
    type: PizzaTypes.chill,
    typeAdv: PizzaTypes.spicy,
    typeWeak: PizzaTypes.fungi,
    src: "/images/characters/pizzas/c001.png",
    icon: "/images/icons/chill.png",
    actions: ["damage1", "chill1", "frozenStatus"],
    baseStats: {
      hp: 26,
      vitRate: 2,
      atk: 10,
      atkRate: 1,
      def: 10,
      defRate: 2,
      spd: 4,
      spdRate: 4,
    },
  },
  c002: {
    name: "Margherita Mellow",
    description: "A Tomato-basil bombshell",
    type: PizzaTypes.chill,
    typeAdv: PizzaTypes.spicy,
    typeWeak: PizzaTypes.fungi,
    src: "/images/characters/pizzas/c002.png",
    icon: "/images/icons/chill.png",
    actions: ["chill1", "chill+saucy1", "dot1", "damage2"],
    baseStats: {
      hp: 21,
      vitRate: 2,
      atk: 11,
      atkRate: 2,
      def: 9,
      defRate: 4,
      spd: 9,
      spdRate: 1,
    },
  },
};
