window.Tunes = {
  title: new Audio("./../Audio/Utopia.ogg"),
  erio: new Audio("./../Audio/Tower.ogg"),
  learning: new Audio("./../Audio/NewJourney.ogg"),
  beth: new Audio("./../Audio/Sky.ogg"),
  town: new Audio("./../Audio/Town.ogg"),
  upperTown: new Audio("./../Audio/Field4.ogg"),
  basicBattle: new Audio("./../Audio/Battle1.ogg"),
  battlingHard: new Audio("./../Audio/Battle2.ogg"),
  bossElvis: new Audio("./../Audio/Boss1.ogg"),
  bossErio: new Audio("./../Audio/Boss2.ogg"),
  badEnd: new Audio("./../Audio/Farewell.ogg"),
  goodEnd: new Audio("./../Audio/Ending.ogg"),
  secretMap: new Audio("./../Audio/Glacier.ogg"),
  spinachBattle: new Audio("./../Audio/Battle1.ogg"),
};
