window.DungeonRooms = {
  a: {
    uniqueId: "a",
    name: "startUp",
    top: null,
    right: false,
    left: false,
    bottom: false,
  },
  b: {
    uniqueId: "b",
    name: "dead-bottom",
    top: null,
    right: false,
    left: false,
    bottom: false,
  },
  c: {
    uniqueId: "c",
    name: "straightLine1",
    top: null,
    bottom: null,
    right: false,
    left: false,
  },
  d: {
    uniqueId: "d",
    name: "straightLine2",
    left: null,
    right: null,
    top: false,
    bottom: false,
  },
  e: {
    uniqueId: "e",
    name: "NEturn",
    top: null,
    right: null,
    left: false,
    bottom: false,
  },
  f: {
    uniqueId: "f",
    name: "NWturn",
    top: null,
    left: null,
    right: false,
    bottom: false,
  },
  g: {
    uniqueId: "g",
    name: "SWturn",
    left: null,
    bottom: null,
    top: false,
    right: false,
  },
  h: {
    uniqueId: "h",
    name: "SEturn",
    right: null,
    bottom: null,
    top: false,
    left: false,
  },
  i: {
    uniqueId: "i",
    name: "E3Point",
    top: null,
    right: null,
    bottom: null,
    left: false,
  },
  j: {
    uniqueId: "j",
    name: "W3Point",
    top: null,
    left: null,
    bottom: null,
    right: false,
  },
  k: {
    uniqueId: "k",
    name: "S3Point",
    right: null,
    left: null,
    bottom: null,
    top: false,
  },
  l: {
    uniqueId: "l",
    name: "N3Point",
    top: null,
    right: null,
    left: null,
    bottom: false,
  },
  m: {
    uniqueId: "m",
    name: "t-cross",
    left: null,
    top: null,
    right: null,
    bottom: null,
  },
  n: {
    uniqueId: "n",
    name: "t-crossSquare",
    left: null,
    top: null,
    right: null,
    bottom: null,
  },
  o: {
    uniqueId: "o",
    name: "deadBox-top",
    bottom: null,
    top: false,
    right: false,
    left: false,
  },
  p: {
    uniqueId: "p",
    name: "W3Curve",
    left: null,
    bottom: null,
    top: null,
    right: false,
  },
  q: {
    uniqueId: "q",
    name: "E3Curve",
    top: null,
    right: null,
    bottom: null,
    left: false,
  },
  r: {
    uniqueId: "r",
    name: "StraightBox",
    top: null,
    bottom: null,
    right: false,
    left: false,
  },
  s: {
    uniqueId: "s",
    name: "upBox",
    right: null,
    left: null,
    top: false,
    bottom: false,
  },
  t: {
    uniqueId: "t",
    name: "t-crossBox",
    top: null,
    right: null,
    left: null,
    bottom: null,
  },
  u: {
    uniqueId: "u",
    name: "deadCross-top",
    bottom: null,
    top: false,
    right: false,
    left: false,
  },
  v: {
    uniqueId: "v",
    name: "deadCurve-bottom",
    top: null,
    bottom: false,
    right: false,
    left: false,
  },
  w: {
    uniqueId: "w",
    name: "dead-left",
    right: null,
    left: false,
    top: false,
    bottom: false,
  },
  x: {
    uniqueId: "x",
    name: "dead-right",
    left: null,
    right: false,
    top: false,
    bottom: false,
  },
  y: {
    uniqueId: "y",
    name: "dead-top",
    bottom: null,
    top: false,
    right: false,
    left: false,
  },
  z: {
    uniqueId: "z",
    name: "deadEndUp",
    bottom: null,
    top: false,
    left: false,
    right: false,
  },
  za: {
    uniqueId: "za",
    name: "deadEndDown",
    top: null,
    right: false,
    left: false,
    bottom: false,
  },
  zb: {
    uniqueId: "zb",
    name: "deadEndright",
    left: null,
    top: false,
    right: false,
    bottom: false,
  },
  zc: {
    uniqueId: "zc",
    name: "deadEndLeft",
    right: null,
    top: false,
    left: false,
    bottom: false,
  },
};
